on: [push]

name: testup

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Generate remappings
        run: |
          forge remappings
          forge remappings > remappings.txt
          echo 'src/=/app/src/' >> remappings.txt

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot

